export const GAME = {
  MIN_PLAYERS: 4,
  MAX_PLAYERS: 8,
  MAFIA_PER_N: 4,
  NIGHT_DURATION: 30,
  DAY_DURATION: 60,
  DISCUSSION_DURATION: 40,
  VOTE_DURATION: 20,
  ROOM_CODE_LENGTH: 4,
  ROOM_GC_CHECK_INTERVAL_MS: 30_000,
  ROOM_GC_ABANDON_THRESHOLD_MS: 120_000,
};
