export const GAME = {
  MIN_PLAYERS: 4,
  MAX_PLAYERS: 8,
  MAFIA_PER_N: 4,
  NIGHT_DURATION: 30,
  DAY_DURATION: 60,
  DISCUSSION_DURATION: 40,
  VOTE_DURATION: 20,
  ROOM_CODE_LENGTH: 4,
};

export const ADS = {
  INTERSTITIAL_EVERY_N_GAMES: 3,
  FIRST_AD_AFTER_MINUTES: 2,
  REWARDED_COOLDOWN: 60,
};
