export const GAME = {
  MIN_PLAYERS: 4,
  MAX_PLAYERS: 8,
  DEV_MIN_PLAYERS: 1,
  MAFIA_PER_N: 4,
  NIGHT_DURATION: 30,
  DAY_DURATION: 60,
  DISCUSSION_DURATION: 40,
  VOTE_DURATION: 20,
  ROOM_CODE_LENGTH: 4,
  MAX_ROOM_CODE_ATTEMPTS: 50,
};
